# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "EAPM-plugins"
copyright = "2023, BSC | Barcelona Supercomputing Center"
author = "Barcelona Supercomputing Center"
release = "0.2"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    "nbsphinx",
    "sphinx_copybutton",
    "sphinx_design",
]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_static_path = ["_static"]
templates_path = ["_templates"]

# -- Options --

source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "pydata_sphinx_theme"
# html_theme = "sphinx_book_theme"
# html_static_path = ["_static"]
html_logo = "_static/eapm.jpg"
html_favicon = "_static/eapm.jpg"
html_show_sourcelink = False
html_show_sphinx = False
html_theme_options = {"collapse_navigation": True}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    # TODO not ready yet
    "show_nav_level": 1,
    "logo": {
        "text": "EAPM-plugins",
        "image_dark": "eapm.jpg",
        "alt_text": "eapm logo",
    },
    "icon_links": [
        {
            "name": "Barcelona Supercomputing Centre website",
            "url": "https://www.bsc.es/",
            "icon": "fa fa-globe",
        },
        {
            "name": "Twitter",
            "url": "https://www.twitter.com/EAPM_BSC",
            "icon": "fa-brands fa-twitter",
        },
        {
            "name": "Linkedin",
            "url": "https://www.linkedin.com/company/barcelona-supercomputing-center/",
            "icon": "fa-brands fa-linkedin",
        },
    ],
    # "switcher": {
    #    "json_url": "https://mysite.org/en/latest/_static/switcher.json",
    # }
}

add_module_names = False
autoclass_content = "both"
